parameters:
    tagcache.factory:             RickySu\TagcacheBundle\TagcacheFactory
    tagcache.Tagcache.Adapter:    RickySu\TagcacheBundle\Tagcache\TagcacheAdapter

services:
        tagcache:
            class:                 %tagcache.Tagcache.Adapter%
            factory_class:         %tagcache.factory%
            factory_method:        getInstance
            arguments:
                -                  %tagcache%
        action_cache_listener_service:
            class:                 RickySu\TagcacheBundle\EventListener\ActionCacheListener
            arguments:             ['@service_container','@controller_resolver',%tagcache%]
            tags:
                 #request lower priority
                 #response higher priority
                                   - { name: kernel.event_listener, event: kernel.request, method: handleRequest  ,priority: -999 }
                                   - { name: kernel.event_listener, event: kernel.response, method: handleResponse  ,priority: 999 }
